basePath: /api/v1
definitions:
  EmailID:
    properties:
      email:
        type: string
      id:
        type: string
      profileId:
        type: string
    type: object
  github_com_adeyemialameen04_unwind-be_core_server.InternalServerErrorResponse:
    properties:
      errors: {}
      message:
        type: string
      status:
        example: Internal Server Error
        type: string
    type: object
  github_com_adeyemialameen04_unwind-be_core_server.NotFoundResponse:
    properties:
      errors: {}
      message:
        type: string
      status:
        example: Not Found
        type: string
    type: object
  github_com_adeyemialameen04_unwind-be_core_server.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status:
        type: string
    type: object
  github_com_adeyemialameen04_unwind-be_core_server.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        example: OK
        type: string
    type: object
  github_com_adeyemialameen04_unwind-be_core_server.UnauthorizedResponse:
    properties:
      errors: {}
      message:
        type: string
      status:
        example: Unauthorized
        type: string
    type: object
  github_com_adeyemialameen04_unwind-be_internal_db_repository.Profile:
    properties:
      coverPic:
        type: string
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      profilePic:
        type: string
      updatedAt:
        type: string
      userId:
        type: string
      username:
        minLength: 8
        type: string
    required:
    - userId
    - username
    type: object
  github_com_adeyemialameen04_unwind-be_internal_db_repository.RegisterUserParams:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_adeyemialameen04_unwind-be_internal_db_repository.UpdateProfileParams:
    properties:
      coverPic:
        type: string
      id:
        type: string
      name:
        type: string
      profilePic:
        type: string
      username:
        minLength: 8
        type: string
    required:
    - username
    type: object
  github_com_adeyemialameen04_unwind-be_internal_db_repository.WatchList:
    properties:
      anilistId:
        type: string
      createdAt:
        type: string
      hianimeId:
        type: string
      id:
        type: string
      updatedAt:
        type: string
      userId:
        type: string
    required:
    - anilistId
    - hianimeId
    type: object
  github_com_adeyemialameen04_unwind-be_internal_domain.AuthResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/EmailID'
    type: object
  github_com_adeyemialameen04_unwind-be_internal_domain.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  github_com_adeyemialameen04_unwind-be_internal_utils.TokenPair:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: adeyemialameen04@gmail.com
    name: Al-Ameen Adeyemi
    url: https://github.com/adeyemialameen04
  description: API for Unwind
  title: Unwind API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Logs a user into his/her account
      parameters:
      - description: Login data
        in: body
        name: EmailAndPassword
        required: true
        schema:
          $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.RegisterUserParams'
      produces:
      - application/json
      responses:
        "201":
          description: Login success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_domain.AuthResponse'
              type: object
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.InternalServerErrorResponse'
      summary: Login to your account
      tags:
      - Auth
  /auth/refresh:
    get:
      consumes:
      - application/json
      description: Refreshes token to get new token pair
      produces:
      - application/json
      responses:
        "200":
          description: TokenPair
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_utils.TokenPair'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.UnauthorizedResponse'
        "404":
          description: Profile not found
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.NotFoundResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.InternalServerErrorResponse'
      security:
      - RefreshTokenBearer: []
      summary: Refresh Token
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create an account on unwind
      parameters:
      - description: Signup data
        in: body
        name: EmailAndPassword
        required: true
        schema:
          $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_domain.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_domain.AuthResponse'
              type: object
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.InternalServerErrorResponse'
      summary: Create an account
      tags:
      - Auth
  /user/profile:
    get:
      consumes:
      - application/json
      description: Retrieves a user profile
      parameters:
      - description: Profile Data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.UpdateProfileParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.Profile'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.UnauthorizedResponse'
        "404":
          description: Profile not found
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.NotFoundResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.InternalServerErrorResponse'
      security:
      - AccessTokenBearer: []
      summary: Get Profile
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Updates a user profile including optional profile and cover pictures
      parameters:
      - description: Profile Data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.UpdateProfileParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.Profile'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.UnauthorizedResponse'
        "404":
          description: Profile not found
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.NotFoundResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.InternalServerErrorResponse'
      security:
      - AccessTokenBearer: []
      summary: Update Profile
      tags:
      - User
  /user/watch-list:
    get:
      consumes:
      - application/json
      description: Retrieves a user watch list.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.WatchList'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.UnauthorizedResponse'
        "404":
          description: Profile not found
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.NotFoundResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.InternalServerErrorResponse'
      security:
      - AccessTokenBearer: []
      summary: Get User WatchList
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  AccessTokenBearer:
    description: AccessTokenBearer Authentication
    in: header
    name: Authorization
    type: apiKey
  RefreshTokenBearer:
    description: RefreshTokenBearer Authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Authentication endpoints
  name: Auth
