basePath: /api/v1
definitions:
  EmailID:
    properties:
      email:
        type: string
      id:
        type: string
    type: object
  core_handlers_auth.RegisterResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/EmailID'
    type: object
  github_com_adeyemialameen04_unwind-be_core_server.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status:
        type: string
    type: object
  github_com_adeyemialameen04_unwind-be_internal_db_repository.Book:
    properties:
      author:
        type: string
      createdAt:
        type: string
      id:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    required:
    - author
    - title
    type: object
  github_com_adeyemialameen04_unwind-be_internal_db_repository.InsertBookParams:
    properties:
      author:
        type: string
      title:
        type: string
    required:
    - author
    - title
    type: object
  github_com_adeyemialameen04_unwind-be_internal_db_repository.RegisterUserParams:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: adeyemialameen04@gmail.com
    name: Al-Ameen Adeyemi
    url: https://github.com/adeyemialameen04
  description: API for Unwind
  title: Unwind API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Logs a user into his/her account
      parameters:
      - description: Login data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.RegisterUserParams'
      produces:
      - application/json
      responses:
        "201":
          description: Login success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.Response'
            - properties:
                data:
                  $ref: '#/definitions/core_handlers_auth.RegisterResponse'
              type: object
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to start transaction or insert book
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login to your account
      tags:
      - Auth
  /auth/refresh:
    get:
      consumes:
      - application/json
      description: Refreshes token to get new token pair
      produces:
      - application/json
      responses: {}
      summary: Refreh Token
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create an account on unwind
      parameters:
      - description: Signup data
        in: body
        name: EmailAndPassword
        required: true
        schema:
          $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.RegisterUserParams'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.Response'
            - properties:
                data:
                  $ref: '#/definitions/core_handlers_auth.RegisterResponse'
              type: object
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to start transaction or insert book
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create an account
      tags:
      - Auth
  /books:
    get:
      consumes:
      - application/json
      description: Get a list of all books
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Books retrieved successfully
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.Book'
                  type: array
              type: object
      summary: Get all books
      tags:
      - Books
    post:
      consumes:
      - application/json
      description: Insert a new book into the database
      parameters:
      - description: Book data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.InsertBookParams'
      produces:
      - application/json
      responses:
        "201":
          description: Book created successfully
          schema:
            allOf:
            - $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_core_server.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.Book'
              type: object
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to start transaction or insert book
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - AccessTokenBearer: []
      summary: Create a new book
      tags:
      - Books
securityDefinitions:
  AccessTokenBearer:
    description: AccessTokenBearer Authentication
    in: header
    name: Authorization
    type: apiKey
  RefreshTokenBearer:
    description: RefreshTokenBearer Authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Authentication endpoints
  name: Auth
