definitions:
  github_com_adeyemialameen04_unwind-be_internal_db_repository.Book:
    properties:
      author:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  github_com_adeyemialameen04_unwind-be_internal_db_repository.InsertBookParams:
    properties:
      author:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Al-Ameen Adeyemi
  description: Api for Unwind
  title: Unwind Api
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get a list of all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.Book'
            type: array
      summary: Get all books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Insert a new book into the database
      parameters:
      - description: Book data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.InsertBookParams'
      produces:
      - application/json
      responses:
        "201":
          description: Book created successfully
          schema:
            $ref: '#/definitions/github_com_adeyemialameen04_unwind-be_internal_db_repository.Book'
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to start transaction or insert book
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new book
      tags:
      - books
swagger: "2.0"
