definitions:
  types.Book:
    properties:
      author:
        type: string
      id:
        type: string
      quantity:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Al-Ameen Adeyemi
  description: Api for Unwind
  title: Unwind Api
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get a list of all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Book'
            type: array
      summary: Get all books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Create a new book with the provided data
      parameters:
      - description: Book data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/types.Book'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Book'
      summary: Create a new book
      tags:
      - books
swagger: "2.0"
